### ISSUE TITLE
运行项目的时候出现了SSL连接失败的报错

### ISSUE THREAD

**Issue by i-rong** [CocaineCong/tangseng#49]
如题，报错信息如下：
```
python main.py
Traceback (most recent call last):
  File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/rong/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/rong/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f6d3b474cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rong/.local/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/rong/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/uer/sbert-base-chinese-nli (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d3b474cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/Codespace/tangseng/main.py", line 14, in <module>
    from app.search_vector.service.search_vector import serve
  File "/mnt/d/Codespace/tangseng/app/search_vector/service/search_vector.py", line 9, in <module>
    from ..config.config import DEFAULT_MILVUS_TABLE_NAME, VECTOR_ADDR
  File "/mnt/d/Codespace/tangseng/app/search_vector/config/config.py", line 78, in <module>
    TRANSFORMER_MODEL = SentenceTransformer(TRANSFORMER_MODEL_NAME)
  File "/home/rong/.local/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 87, in __init__
    snapshot_download(model_name_or_path,
  File "/home/rong/.local/lib/python3.10/site-packages/sentence_transformers/util.py", line 442, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
  File "/home/rong/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/rong/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1677, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "/home/rong/.local/lib/python3.10/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/home/rong/.local/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rong/.local/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/rong/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/home/rong/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/uer/sbert-base-chinese-nli (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d3b474cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: ab538c3f-6bbc-4c72-901e-38b7ecef0529)')
```
想请问这个要怎么解决哇？

**Comment by ozline** [comment]
似乎是网络连接不畅，有给 shell 挂代理吗？

**Comment by CocaineCong** [comment]
> 如题，报错信息如下：
> 
> ```
> Codespace/tangseng$ python main.py
> Traceback (most recent call last):
>   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
>     raise err
>   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
>     sock.connect(sa)
> OSError: [Errno 101] Network is unreachable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
>     httplib_response = self._make_request(
>   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
>     self._validate_conn(conn)
>   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
>     conn.connect()
>   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
>     self.sock = conn = self._new_conn()
>   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f6d3b474cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/rong/.local/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
>     resp = conn.urlopen(
>   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
>     retries = retries.increment(
>   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/uer/sbert-base-chinese-nli (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d3b474cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/mnt/d/Codespace/tangseng/main.py", line 14, in <module>
>     from app.search_vector.service.search_vector import serve
>   File "/mnt/d/Codespace/tangseng/app/search_vector/service/search_vector.py", line 9, in <module>
>     from ..config.config import DEFAULT_MILVUS_TABLE_NAME, VECTOR_ADDR
>   File "/mnt/d/Codespace/tangseng/app/search_vector/config/config.py", line 78, in <module>
>     TRANSFORMER_MODEL = SentenceTransformer(TRANSFORMER_MODEL_NAME)
>   File "/home/rong/.local/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 87, in __init__
>     snapshot_download(model_name_or_path,
>   File "/home/rong/.local/lib/python3.10/site-packages/sentence_transformers/util.py", line 442, in snapshot_download
>     model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
>   File "/home/rong/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
>     return fn(*args, **kwargs)
>   File "/home/rong/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1677, in model_info
>     r = get_session().get(path, headers=headers, timeout=timeout, params=params)
>   File "/home/rong/.local/lib/python3.10/site-packages/requests/sessions.py", line 542, in get
>     return self.request('GET', url, **kwargs)
>   File "/home/rong/.local/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/rong/.local/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/rong/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
>     return super().send(request, *args, **kwargs)
>   File "/home/rong/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/uer/sbert-base-chinese-nli (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d3b474cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: ab538c3f-6bbc-4c72-901e-38b7ecef0529)')
> ```
> 
> 想请问这个要怎么解决哇？

你能简单讲讲你的操作流程吗？或者复现这个问题的步骤？

**Comment by i-rong** [comment]
> > 如题，报错信息如下：
> > ```
> > Codespace/tangseng$ python main.py
> > Traceback (most recent call last):
> >   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
> >     conn = connection.create_connection(
> >   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
> >     raise err
> >   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
> >     sock.connect(sa)
> > OSError: [Errno 101] Network is unreachable
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
> >     httplib_response = self._make_request(
> >   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
> >     self._validate_conn(conn)
> >   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
> >     conn.connect()
> >   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
> >     self.sock = conn = self._new_conn()
> >   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
> >     raise NewConnectionError(
> > urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f6d3b474cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/home/rong/.local/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
> >     resp = conn.urlopen(
> >   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
> >     retries = retries.increment(
> >   File "/home/rong/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
> >     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> > urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/uer/sbert-base-chinese-nli (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d3b474cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/mnt/d/Codespace/tangseng/main.py", line 14, in <module>
> >     from app.search_vector.service.search_vector import serve
> >   File "/mnt/d/Codespace/tangseng/app/search_vector/service/search_vector.py", line 9, in <module>
> >     from ..config.config import DEFAULT_MILVUS_TABLE_NAME, VECTOR_ADDR
> >   File "/mnt/d/Codespace/tangseng/app/search_vector/config/config.py", line 78, in <module>
> >     TRANSFORMER_MODEL = SentenceTransformer(TRANSFORMER_MODEL_NAME)
> >   File "/home/rong/.local/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 87, in __init__
> >     snapshot_download(model_name_or_path,
> >   File "/home/rong/.local/lib/python3.10/site-packages/sentence_transformers/util.py", line 442, in snapshot_download
> >     model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
> >   File "/home/rong/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
> >     return fn(*args, **kwargs)
> >   File "/home/rong/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1677, in model_info
> >     r = get_session().get(path, headers=headers, timeout=timeout, params=params)
> >   File "/home/rong/.local/lib/python3.10/site-packages/requests/sessions.py", line 542, in get
> >     return self.request('GET', url, **kwargs)
> >   File "/home/rong/.local/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
> >     resp = self.send(prep, **send_kwargs)
> >   File "/home/rong/.local/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
> >     r = adapter.send(request, **kwargs)
> >   File "/home/rong/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
> >     return super().send(request, *args, **kwargs)
> >   File "/home/rong/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
> >     raise ConnectionError(e, request=request)
> > requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/uer/sbert-base-chinese-nli (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d3b474cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: ab538c3f-6bbc-4c72-901e-38b7ecef0529)')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 想请问这个要怎么解决哇？
> 
> 你能简单讲讲你的操作流程吗？或者复现这个问题的步骤？

ok了，已经解决了。使用国内的镜像网站就可以  问题的原因是本地无法连接到hf
[国内镜像网站链接](https://hf-mirror.com/)
